### PR TITLE
add jalebi

### PR DESCRIPTION
**Pull request by iamsj7**

### CODE REVIEW

**Comment by premaca** [comment]
devices in vendor are for officially supported devices. For unofficial devices, add vendorsetup.sh in your device tree along with lunch combo.

**Comment by iamsj7** [comment]
I am willing to maintain it official :)

**Comment by Martinusbe** [comment]
many are willing, not many make it

**Comment by Shrayanshy** [comment]
But I do 
Still I didn't get

**Comment by Martinusbe** [comment]
and we can't merge pull requests on gzosp, need to go over gerrit
https://review.gzospgzr.com

**Pull request closed without merging**
